// emailService.js - CORRECTED VERSION
import nodemailer from 'nodemailer';

// Create transporter
const createTransporter = () => {
  console.log('[EmailService] Creating transporter with:', {
    user: process.env.EMAIL_USER,
    hasPass: !!process.env.EMAIL_PASS
  });
  
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS, // Use App Password for Gmail
    },
  });
};

// Generate HTML template for itinerary email
const generateItineraryHTML = (trip, itinerary, budget, weather) => {
  const duration = Math.ceil((new Date(trip.end_date) - new Date(trip.start_date)) / (1000 * 60 * 60 * 24));
  
  return `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .section { background: #f9f9f9; margin: 20px 0; padding: 20px; border-radius: 10px; }
        .day-plan { background: white; margin: 15px 0; padding: 15px; border-left: 4px solid #667eea; }
        .budget-item { display: flex; justify-content: space-between; margin: 8px 0; }
        .total { font-weight: bold; border-top: 2px solid #ddd; padding-top: 10px; }
        .weather-day { display: inline-block; margin: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🌍 Your Trip to ${trip.destination}</h1>
        <p>${new Date(trip.start_date).toLocaleDateString()} - ${new Date(trip.end_date).toLocaleDateString()} (${duration} days)</p>
    </div>
    
    <div class="container">
        <div class="section">
            <h2>📅 Trip Overview</h2>
            <p><strong>Destination:</strong> ${trip.destination}</p>
            <p><strong>Duration:</strong> ${duration} days</p>
            <p><strong>Travelers:</strong> ${trip.adults || 1} adult(s)</p>
            <p><strong>Total Budget:</strong> $${budget?.total || 0}</p>
        </div>

        <div class="section">
            <h2>💰 Budget Breakdown</h2>
            ${budget?.breakdown ? Object.entries(budget.breakdown).map(([category, amount]) => `
                <div class="budget-item">
                    <span>${category.charAt(0).toUpperCase() + category.slice(1)}:</span>
                    <span>$${amount}</span>
                </div>
            `).join('') : '<p>No budget data available</p>'}
            <div class="budget-item total">
                <span>Total:</span>
                <span>$${budget?.total || 0}</span>
            </div>
        </div>

        <div class="section">
            <h2>🗓️ Daily Itinerary</h2>
            ${itinerary && itinerary.length > 0 ? itinerary.map(day => `
                <div class="day-plan">
                    <h3>Day ${day.day}: ${day.date}</h3>
                    ${day.weather ? `<p><strong>Weather:</strong> ${day.weather.condition}, ${day.weather.temp_high}°C / ${day.weather.temp_low}°C</p>` : ''}
                    <p><strong>Activities:</strong></p>
                    <ul>
                        ${day.places && day.places.length > 0 ? day.places.map(place => `
                            <li>${place.name} (${place.suggested_time_hrs} hrs) - ${place.description || 'No description'}</li>
                        `).join('') : '<li>No activities planned</li>'}
                    </ul>
                    <p><strong>Estimated Daily Budget:</strong> $${day.budget?.daily_estimated || 0}</p>
                </div>
            `).join('') : '<p>No itinerary generated yet.</p>'}
        </div>

        <div class="section">
            <h2>💡 Travel Tips</h2>
            <ul>
                <li>Keep digital and physical copies of important documents</li>
                <li>Check local COVID-19 guidelines and travel restrictions</li>
                <li>Notify your bank about international travel</li>
                <li>Download offline maps and translation apps</li>
                <li>Purchase travel insurance for peace of mind</li>
            </ul>
        </div>

        <div style="text-align: center; margin-top: 30px; padding: 20px; background: #f0f0f0; border-radius: 10px;">
            <p>Happy travels! 🎉</p>
            <p><em>This itinerary was generated by your Travel Planning Assistant</em></p>
        </div>
    </div>
</body>
</html>
  `;
};


// Generate HTML for recommendation email (NEW - for cron jobs)
const generateRecommendationHTML = (destination, recommendations) => {
  return `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
        .container { padding: 20px; }
        .recommendation { background: #f8f9fa; margin: 20px 0; padding: 20px; border-radius: 10px; border-left: 4px solid #667eea; }
        .category { display: inline-block; background: #667eea; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; margin-bottom: 10px; }
        .pro-tip { background: #fff3cd; padding: 10px; border-radius: 5px; margin-top: 10px; font-style: italic; }
        .seasonal-highlight { background: #e7f3ff; padding: 20px; border-radius: 10px; margin: 20px 0; }
        .footer { text-align: center; margin-top: 30px; padding: 20px; background: #f0f0f0; border-radius: 10px; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>✨ Your Personalized Travel Guide</h1>
        <p>Fresh recommendations for ${destination}</p>
    </div>
    
    <div class="container">
        <h2>${recommendations.greeting}</h2>
        
        <p>Based on your travel history and current trends, here are some amazing places you might love:</p>
        
        ${recommendations.recommendations.map(rec => `
            <div class="recommendation">
                <span class="category">${rec.category}</span>
                <h3>${rec.title}</h3>
                <p>${rec.description}</p>
                <p><strong>Why now:</strong> ${rec.why_now}</p>
                <div class="pro-tip">
                    <strong>💡 Pro Tip:</strong> ${rec.pro_tip}
                </div>
            </div>
        `).join('')}
        
        <div class="seasonal-highlight">
            <h3>🌸 Seasonal Highlight</h3>
            <p>${recommendations.seasonal_highlight}</p>
        </div>
        
        <p style="font-size: 16px; line-height: 1.8;">${recommendations.closing}</p>
        
        <div class="footer">
            <p>Happy exploring! 🎉</p>
            <p><em>Your Travel Planning Assistant</em></p>
            <p>
                You're receiving this because you've used our travel planning services.<br>
                <a href="#" style="color: #667eea; text-decoration: none;">Unsubscribe</a> from these recommendations.
            </p>
        </div>
    </div>
</body>
</html>
  `;
};


// Send itinerary email
export const sendItineraryEmail = async (userEmail, trip, itineraryData, budgetData, weatherData) => {
  try {
    console.log(`[EmailService] Attempting to send email to: ${userEmail}`);
    
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error('Email credentials not configured. Please set EMAIL_USER and EMAIL_PASS environment variables.');
    }

    const transporter = createTransporter();
    
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: userEmail,
      subject: `✈️ Your Travel Itinerary for ${trip.destination}`,
      html: generateItineraryHTML(trip, itineraryData, budgetData, weatherData),
    };

    console.log('[EmailService] Sending email...');
    const result = await transporter.sendMail(mailOptions);
    console.log(`✅ Itinerary email sent to ${userEmail}, Message ID: ${result.messageId}`);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    console.error('❌ Failed to send itinerary email:', error);
    throw new Error(`Email sending failed: ${error.message}`);
  }
};


// Send recommendation email (NEW - for cron jobs)
export const sendRecommendationEmail = async (userEmail, destination, recommendations) => {
  try {
    console.log(`[EmailService] Attempting to send recommendation email to: ${userEmail}`);
    
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error('Email credentials not configured. Please set EMAIL_USER and EMAIL_PASS environment variables.');
    }

    const transporter = createTransporter();
    
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: userEmail,
      subject: `✨ Travel Inspiration: New Places to Explore in ${destination}`,
      html: generateRecommendationHTML(destination, recommendations),
    };

    console.log('[EmailService] Sending recommendation email...');
    const result = await transporter.sendMail(mailOptions);
    console.log(`✅ Recommendation email sent to ${userEmail}, Message ID: ${result.messageId}`);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    console.error('❌ Failed to send recommendation email:', error);
    throw new Error(`Recommendation email failed: ${error.message}`);
  }
};




// Send simple notification email
export const sendNotificationEmail = async (userEmail, subject, message) => {
  try {
    console.log(`[EmailService] Sending notification email to: ${userEmail}`);
    
    const transporter = createTransporter();
    
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: userEmail,
      subject: subject,
      text: message,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center;">
            <h2>Travel Buddy Notification</h2>
          </div>
          <div style="padding: 20px;">
            <p>${message.replace(/\n/g, '<br>')}</p>
          </div>
          <div style="text-align: center; padding: 20px; background: #f0f0f0;">
            <p><em>Your Travel Planning Assistant</em></p>
          </div>
        </div>
      `
    };

    const result = await transporter.sendMail(mailOptions);
    console.log(`✅ Notification email sent to ${userEmail}`);
    return { success: true, messageId: result.messageId };
  } catch (error) {
    console.error('❌ Failed to send notification email:', error);
    throw error;
  }
};

// Test email connection (NEW - for debugging)
export const testEmailConnection = async () => {
  try {
    console.log('[EmailService] Testing email connection...');
    
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error('Email credentials not configured');
    }

    const transporter = createTransporter();
    
    // Verify connection configuration
    await transporter.verify();
    console.log('✅ Email server connection verified successfully');
    
    // Send test email
    const testResult = await sendNotificationEmail(
      process.env.EMAIL_USER, // Send to yourself
      '📧 Travel Buddy - Email Test',
      'This is a test email to verify your email configuration is working correctly.\n\nIf you received this, your email setup is successful!'
    );
    
    console.log('✅ Test email sent successfully');
    return { success: true, message: 'Email configuration is working correctly' };
  } catch (error) {
    console.error('❌ Email connection test failed:', error);
    throw new Error(`Email test failed: ${error.message}`);
  }
};

// Export the transporter creation function for external use
export { createTransporter };